### PR TITLE
Update feedstock for v0.5.0-rc2

### PR DESCRIPTION
**Pull request by goerz**
I'm manually creating this PR since the `regro-cf-auotick-bot` didn't pick up on the PyPI Release.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by goerz** [comment]
@conda-forge-admin, please rerender

**Comment by goerz** [comment]
I was trying to clarify how the feedstock update ist supposed to work at https://gitter.im/conda-forge/regro-cf-autotick-bot, but no luck there.

**Comment by goerz** [comment]
Isn't some bot supposed to make a second "MNT" commit, like at https://github.com/conda-forge/doctr-versions-menu-feedstock/pull/1/commits?

**Comment by hhslepicka** [comment]
@goerz I may be wrong but usually `rc` versions don't show up on conda-forge.
The bot works fine to open the PR with the new version once the code is released on PyPI but sometimes it just takes a bit longer.

About the `MNT` commit from `rerender` sometimes it is not necessary to rerender the recipe as there were no changes upstream on pinning, CI and etc... so that is normal and the bot answered to your request here: https://github.com/conda-forge/docs-versions-menu-feedstock/pull/1#issuecomment-814329379

**Comment by hhslepicka** [comment]
Here is an issue opened a while ago about `prereleases`: https://github.com/conda-forge/conda-forge.github.io/issues/147

**Comment by goerz** [comment]
> @goerz I may be wrong but usually `rc` versions don't show up on conda-forge.

I thought that might be the case. I just doesn't seem like the bot behavior is documented anywhere...

> The bot works fine to open the PR with the new version once the code is released on PyPI but sometimes it just takes a bit longer.

Yes, it seems like it has picked up quite well on "proper" releases for doctr-versions-menu in the past. Again, I'm just not finding much documentation about how all this "magic" infrastructure works. ;-)


> About the `MNT` commit from `rerender` sometimes it is not necessary to rerender the recipe as there were no changes upstream on pinning, CI and etc... so that is normal and the bot answered to your request here: [#1 (comment)](https://github.com/conda-forge/docs-versions-menu-feedstock/pull/1#issuecomment-814329379)

Right, because none of the conditions in https://conda-forge.org/docs/maintainer/updating_pkgs.html#when-to-rerender are met?

So does that mean that you or I can now merge this PR, and the package will be updated to 0.5.0-rc2 on [conda-forge](https://anaconda.org/conda-forge/docs-versions-menu) automatically?

**Comment by hhslepicka** [comment]
> Right, because none of the conditions in https://conda-forge.org/docs/maintainer/updating_pkgs.html#when-to-rerender are met?

Correct!

> So does that mean that you or I can now merge this PR, and the package will be updated to 0.5.0-rc2 on conda-forge automatically?

That is correct as well... we could just merge it in and seek guidance from conda-forge folks...
If it is not allowed we can remove the artifact easily later on.

**Review by hhslepicka — APPROVED** [review]

**Comment by hhslepicka** [comment]
Here is some guidance on this subject: https://github.com/conda-forge/cfep/blob/master/cfep-05.md

**Pull request merged**
